### ISSUE TITLE
Setup kanban board 

### ISSUE THREAD

**Issue by AlexRS90** [AlexRS90/javascript-capstone#21]
# For this project we:

-Copy the kanban board from the source, you can check it at the following link:

https://github.com/AlexRS90/javascript-capstone/projects/1

## This team has three members:
- Abel Herrera @Lino09 
- Jim Ntare @Ntare22 
- Alejandro Ramos @AlexRS90

**Comment by carlos-ssh** [comment]
# 🍾🍾 **STATUS APPROVED** 👏🏽👏🏽

Hello Team!, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



![Approved](https://user-images.githubusercontent.com/22258274/138466108-6b14c541-6a88-44c5-ba76-c64992ac1835.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
